# Generated by Django 5.0.1 on 2024-02-08 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='nesters',
        ),
    ]
