# Generated by Django 5.0.1 on 2024-02-29 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_users_nesters'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('nester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nesters')),
            ],
        ),
    ]
