# Generated by Django 5.0.1 on 2024-03-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_history_result_alter_input_input_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='extraction_method',
        ),
    ]
