# Generated by Django 5.0.3 on 2024-04-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_input_extraction_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVGFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_file', models.FileField(upload_to='svg_files/')),
            ],
        ),
    ]
