# Generated by Django 5.0.3 on 2024-04-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_svgfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='history',
            new_name='history_m',
        ),
    ]
