# Generated by Django 5.0.3 on 2024-05-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_history_history_m'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='input',
            new_name='Pre_Input',
        ),
    ]
