# Generated by Django 5.0.3 on 2024-05-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_input_pre_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
